---
- name: Deploy karamel into Minikube
  hosts: localhost

  vars:
    purge: true
    strimzi:
      namespace: kafka

  tasks:
    - name: Get Java version
      shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
      register: java_version

    - debug: msg="{{ java_version.stdout }}"

    - assert:
        that:
          - java_version.stdout is version_compare('11', '>=')

    - name: Get Docker env
      shell: minikube docker-env
      register: docker_env

    - name: Delete
      shell: |
        eval {{ docker_env.stdout }}
        kubectl config use-context minikube
        kubectl delete service karamel --grace-period=0 --force -n {{namespace}}
        kubectl delete deployment karamel --grace-period=0 --force -n {{namespace}}
      ignore_errors: yes

    - name: Add permissions
      shell: |
        eval {{ docker_env.stdout }}
        kubectl apply -f karamel.clusterrole.yaml
        kubectl apply -f karamel.serviceaccount.yaml
        kubectl apply -f karamel.clusterrolebinding.yaml

    - name: Compile and package
      shell: |
        cd ../
        mvn clean package

    - name: Build container
      shell: |
        eval {{ docker_env.stdout }}
        cd ../
        docker build -f Dockerfile -t entropy1/karamel .

    - name: Deploy
      shell: kubectl apply -f ../target/kubernetes/minikube.json -n kafka