apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: karamel
  labels:
    app: karamel
subjects:
  - kind: ServiceAccount
    name: karamel
    namespace: kafka
roleRef:
  kind: ClusterRole
  name: karamel
  apiGroup: rbac.authorization.k8s.io